// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mtrack;

namespace sdgreacttemplate.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190712135330_ChangedDBvalues")]
    partial class ChangedDBvalues
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("mtrack.Models.FlightInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alt");

                    b.Property<string>("Altt");

                    b.Property<string>("Call");

                    b.Property<string>("Cou");

                    b.Property<string>("Galt");

                    b.Property<string>("Gnd");

                    b.Property<string>("ICAO");

                    b.Property<string>("Interested");

                    b.Property<string>("Lat");

                    b.Property<string>("Lon");

                    b.Property<string>("Mil");

                    b.Property<string>("Mlat");

                    b.Property<string>("Opicao");

                    b.Property<string>("Pos");

                    b.Property<string>("Postime");

                    b.Property<string>("Reg");

                    b.Property<string>("Sat");

                    b.Property<DateTime>("SaveTime");

                    b.Property<string>("Spd");

                    b.Property<string>("Sqk");

                    b.Property<string>("Talt");

                    b.Property<string>("Tisb");

                    b.Property<string>("Trak");

                    b.Property<string>("Trkh");

                    b.Property<string>("Trt");

                    b.Property<string>("Ttrk");

                    b.Property<string>("Type");

                    b.Property<string>("Vsi");

                    b.Property<string>("Vsit");

                    b.Property<string>("Wtc");

                    b.HasKey("Id");

                    b.ToTable("FlightTable");
                });
#pragma warning restore 612, 618
        }
    }
}
