// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mtrack;

namespace sdgreacttemplate.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("mtrack.Models.FlightInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Alt");

                    b.Property<int>("Altt");

                    b.Property<string>("Call");

                    b.Property<string>("Cou");

                    b.Property<int>("Galt");

                    b.Property<int>("Gnd");

                    b.Property<string>("ICAO");

                    b.Property<int>("Interested");

                    b.Property<int>("Lat");

                    b.Property<int>("Lon");

                    b.Property<int>("Mil");

                    b.Property<int>("Mlat");

                    b.Property<string>("Opicao");

                    b.Property<int>("Pos");

                    b.Property<int>("Postime");

                    b.Property<int>("Reg");

                    b.Property<int>("Sat");

                    b.Property<DateTime>("SaveTime");

                    b.Property<int>("Spd");

                    b.Property<int>("Sqk");

                    b.Property<int>("Talt");

                    b.Property<int>("Tisb");

                    b.Property<int>("Trak");

                    b.Property<int>("Trkh");

                    b.Property<int>("Trt");

                    b.Property<int>("Ttrk");

                    b.Property<string>("Type");

                    b.Property<int>("Vsi");

                    b.Property<int>("Vsit");

                    b.Property<int>("Wtc");

                    b.HasKey("Id");

                    b.ToTable("FlightTable");
                });
#pragma warning restore 612, 618
        }
    }
}
